# task
name: text_concat

# data preprocessing
max_seq_len: 100

# filepaths
data_dir: /data4/tzhu/DocTree/data/text_concat
train_filepath: ${data_dir}/train.json
dev_filepath: ${data_dir}/dev.json
test_filepath: ${data_dir}/test.json
plm_dir: /data4/tzhu/bert_pretrained_models/hfl_rbt3
output_dir: /data4/tzhu/DocTree/outputs
task_dir: ${output_dir}/${name}
score_dir: ${task_dir}/scores
load_train_data: true
load_dev_data: true
load_test_data: true

# training
mode: train  # train或test
debug_mode: false
learning_rate: 1e-5
random_seed: 1234
device: cuda:3
num_epochs: 10
num_early_stop: 5
train_batch_size: 64
eval_batch_size: 64
save_best_ckpt: true

# model
dropout: 0.0
pred_threshold: 0.5
