# task
name: transducer

# data preprocessing
max_seq_len: 100
truncation_strategy: end
use_stream_data_iterator: false

# filepaths
all_data_dir: data/doc_tree_construct/Paper
data_type: DomainMix
data_dir: ${all_data_dir}/${data_type}
plm_dir: /data4/tzhu/bert_pretrained_models/hfl_rbt3
output_dir: paper_outputs
train_filepath: ${data_dir}/train.jsonl
dev_filepath: ${data_dir}/dev.jsonl
test_filepath: ${data_dir}/test.jsonl
task_dir: ${output_dir}/${name}
load_train_data: true
load_dev_data: true
load_test_data: true

# training
skip_train: false
skip_further_train: true
device: cuda:1
local_rank: -1
random_seed: 1227
num_epochs: 10
num_early_stop: 5
train_batch_size: 20
eval_batch_size: 20
learning_rate: 2e-5
save_best_ckpt: true
debug_mode: false
loss_weight: 0.5

# logging
only_master_logging: true

# model
dropout: 0.5
