# task
task_name: pipelined_cls
data_name: DomainMixForPipeline
# data preprocessing
max_seq_len: 100

# filepaths
data_dir: data/doc_tree_construct/Paper/DomainMixForPipeline
plm_dir: /data4/tzhu/bert_pretrained_models/hfl_rbt3
train_filepath: ${data_dir}/train.json
dev_filepath: ${data_dir}/dev.json
test_filepath: ${data_dir}/test.json
output_dir: paper_outputs
task_dir: ${output_dir}/${task_name}/${random_seed}

# training
skip_train: false
skip_final_eval: false
final_eval_model_filepath: ${task_dir}/ckpt/TextClassificationModel.best.pth
skip_predict_example: false
debug_mode: false

device: 5
random_seed: 1227
num_epochs: 3
num_early_stop: 3
train_batch_size: 20
eval_batch_size: 20
learning_rate: !!float 2e-5
save_best_ckpt: true

# logging
only_master_logging: true

# model
dropout: 0.5
num_filters: 300
kernel_sizes: [1, 3, 5]
mid_dims: [100]
